apiVersion: batch/v1
kind: Job
metadata:
  name: "darknet-training"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "darknet-training"
        image: "asia.gcr.io/tikivn/mlflow"
        command: ["python3 src/training/train.py"]
      resources:
        limits:
          memory: 1024Mi
        requests:
          memory: 1024Mi
          nvidia.com/gpu: "1"
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: gpu-4-16
      restartPolicy: Never
      imagePullSecrets:
      - name: tiki-gcr
